# The destination where the Aegis Agent sends data to the Aegis Server. 
agent_control_url=http://localhost:8080

# To control the server, each agent must have a unique host name used for identification. Duplicate host names are not allowed.
agent_host_name=TEST_AGENT

# The socket path used for communication between the agent and the Apache module. It must match the Apache configuration. No changes are required if it has not been modified.
agent_socket_path=/var/run/aegis/agent.sock